include(ExternalProject)

set(CRYPTOPP_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/cryptopp PARENT_SCOPE)

ExternalProject_Add(
  cryptopp
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cryptopp
  CONFIGURE_COMMAND ""
  INSTALL_COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/cryptopp/libcryptopp.a ${CMAKE_CURRENT_BINARY_DIR}/lib.obj
  BUILD_COMMAND make -C ${CMAKE_CURRENT_SOURCE_DIR}/cryptopp
#  BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/lib.obj
  BUILD_IN_SOURCE 1
  LOG_CONFIGURE 1
  LOG_BUILD 1
)
