
set(SECP256K1_INCLUDE_DIRS ${PROJECT_BINARY_DIR}/include/ethcrypto-deps)
if (NOT SECP256K1_USE_CMAKE)
    find_program(AUTORECONF autoreconf)
    if(AUTORECONF)
        include(cmake/secp256k1_autoconf.cmake)
    else()
        include(cmake/secp256k1_cmake.cmake)
    endif()
else()
    include(cmake/secp256k1_cmake.cmake)
endif()
